### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by woanware** [woanware/bgp-watcher#1]
- [x] Need to load data from DB
- [x] Monitor function needs to include all items in data sets
- [x] Use historical data to prioritise alerts
- [x] Add priority to alerts
- [x] Colourise alerts
- [x] Historic data held in memory
- [x] Capture CTRL-C and persist data
- [x] Update data needs to be added to historic data
- [x] Summary function to show current historical data e.g. with countries for each path item, counts
